// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhuWN9AL2gznwJXpZnJ51mbM54hKkDemA',
    appId: '1:7887480139:web:00c9e8877a714afe30f4ce',
    messagingSenderId: '7887480139',
    projectId: 'test-pro-712d2',
    authDomain: 'test-pro-712d2.firebaseapp.com',
    storageBucket: 'test-pro-712d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMEJxRunQuB1-Fb5bHfdlHBrVC5XF3KDw',
    appId: '1:7887480139:android:3bbe020c97ed7b0430f4ce',
    messagingSenderId: '7887480139',
    projectId: 'test-pro-712d2',
    storageBucket: 'test-pro-712d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJisxBnk-tmhSjY6FhBVPPofqBj6goHzQ',
    appId: '1:7887480139:ios:7299b883c2f3554730f4ce',
    messagingSenderId: '7887480139',
    projectId: 'test-pro-712d2',
    storageBucket: 'test-pro-712d2.appspot.com',
    iosClientId: '7887480139-2ljq15jnnpo96mfo9sqstkkpagjrti00.apps.googleusercontent.com',
    iosBundleId: 'com.begali.testPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJisxBnk-tmhSjY6FhBVPPofqBj6goHzQ',
    appId: '1:7887480139:ios:7299b883c2f3554730f4ce',
    messagingSenderId: '7887480139',
    projectId: 'test-pro-712d2',
    storageBucket: 'test-pro-712d2.appspot.com',
    iosClientId: '7887480139-2ljq15jnnpo96mfo9sqstkkpagjrti00.apps.googleusercontent.com',
    iosBundleId: 'com.begali.testPro',
  );
}
